#!/bin/bash

export BOARD=zedboard
#export XILINX_BOARD="xc7z020clg484-1"
#export XILINX_PART="em.avnet.com:zynq:zed:c"
PATH=$PATH:/usr/local/Xilinx/Vivado/2015.1/bin:/usr/local/Xilinx/SDK/2015.1/bin:/usr/local/Xilinx/SDK/2015.1/gnu/arm/lin/bin:/usr/local/riscv/bin
RISCY_RV32F=0

