# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-5876-datorn/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/adam/pulpinomedacc/pulpino/rtl/includes
    /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node
    /home/adam/pulpinomedacc/pulpino/ips/apb/apb_event_unit/include
    /home/adam/pulpinomedacc/pulpino/ips/fpu
    /home/adam/pulpinomedacc/pulpino/ips/apb/apb_i2c
    /home/adam/pulpinomedacc/pulpino/ips/zero-riscy/include
    /home/adam/pulpinomedacc/pulpino/ips/zero-riscy/include
    /home/adam/pulpinomedacc/pulpino/ips/riscv/include
    /home/adam/pulpinomedacc/pulpino/rtl/includes
    /home/adam/pulpinomedacc/pulpino/ips/riscv/include
    /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl
  } -define {PULP_FPGA_EMUL=1 RISCV} {
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_address_decoder_AR.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_address_decoder_AW.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_address_decoder_BR.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_address_decoder_BW.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_address_decoder_DW.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_AR_allocator.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_ArbitrationTree.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_AW_allocator.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_BR_allocator.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_BW_allocator.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_DW_allocator.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_FanInPrimitive_Req.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_multiplexer.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_node.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_request_block.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_response_block.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node/axi_RR_Flag_Req.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_node/apb_node.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_node/apb_node_wrap.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_mem_if_DP/axi_mem_if_SP.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_mem_if_DP/axi_read_only_ctrl.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_mem_if_DP/axi_write_only_ctrl.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_spi_slave/axi_spi_slave.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_spi_slave/spi_slave_axi_plug.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_spi_slave/spi_slave_cmd_parser.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_spi_slave/spi_slave_controller.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_spi_slave/spi_slave_dc_fifo.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_spi_slave/spi_slave_regs.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_spi_slave/spi_slave_rx.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_spi_slave/spi_slave_syncro.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_spi_slave/spi_slave_tx.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_gpio/apb_gpio.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_event_unit/apb_event_unit.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_event_unit/generic_service_unit.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_event_unit/sleep_unit.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_spi_master/apb_spi_master.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_spi_master/spi_master_apb_if.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_spi_master/spi_master_clkgen.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_spi_master/spi_master_controller.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_spi_master/spi_master_fifo.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_spi_master/spi_master_rx.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_spi_master/spi_master_tx.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_utils/fpu_ff.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_defs.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_v0.1/fpexc.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_add.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_core.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_ftoi.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_itof.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_mult.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_norm.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_private.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/fpu_defs_div_sqrt_tp.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/control_tp.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/fpu_norm_div_sqrt.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/iteration_div_sqrt_first.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/iteration_div_sqrt.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/nrbd_nrsc_tp.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/preprocess.sv
      /home/adam/pulpinomedacc/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/div_sqrt_top_tp.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_pulpino/apb_pulpino.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_fll_if/apb_fll_if.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/core2axi/core2axi.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_timer/apb_timer.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_timer/timer.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi2apb/axi2apb.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi2apb/axi2apb32.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_i2c/apb_i2c.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_i2c/i2c_master_bit_ctrl.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_i2c/i2c_master_byte_ctrl.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/include/apu_core_package.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/include/riscv_defines.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_alu.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_alu_div.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_compressed_decoder.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_controller.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_cs_registers.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_debug_unit.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_decoder.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_int_controller.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_ex_stage.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_hwloop_controller.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_hwloop_regs.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_id_stage.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_if_stage.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_load_store_unit.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_mult.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_prefetch_buffer.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_prefetch_L0_buffer.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_core.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_apu_disp.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_fetch_fifo.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_L0_buffer.sv
      /home/adam/pulpinomedacc/pulpino/ips/riscv/riscv_register_file.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice/axi_ar_buffer.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice/axi_aw_buffer.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice/axi_b_buffer.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice/axi_r_buffer.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice/axi_slice.sv
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice/axi_w_buffer.sv
      /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl/adbg_axi_biu.sv
      /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl/adbg_axi_module.sv
      /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_biu.sv
      /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_module.sv
      /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_status_reg.sv
      /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl/adbg_top.sv
      /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl/adv_dbg_if.sv
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb2per/apb2per.sv
      /home/adam/pulpinomedacc/pulpino/rtl/components/cluster_clock_gating.sv
      /home/adam/pulpinomedacc/pulpino/rtl/components/cluster_clock_inverter.sv
      /home/adam/pulpinomedacc/pulpino/rtl/components/cluster_clock_mux2.sv
      /home/adam/pulpinomedacc/pulpino/rtl/components/rstgen.sv
      /home/adam/pulpinomedacc/pulpino/rtl/components/pulp_clock_inverter.sv
      /home/adam/pulpinomedacc/pulpino/rtl/components/pulp_clock_mux2.sv
      /home/adam/pulpinomedacc/pulpino/rtl/components/generic_fifo.sv
      /home/adam/pulpinomedacc/pulpino/rtl/axi2apb_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/periph_bus_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/core2axi_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/axi_node_intf_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/axi_spi_slave_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/axi_slice_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/axi_mem_if_SP_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/core_region.sv
      /home/adam/pulpinomedacc/pulpino/rtl/instr_ram_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/sp_ram_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/boot_code.sv
      /home/adam/pulpinomedacc/pulpino/rtl/boot_rom_wrap.sv
      /home/adam/pulpinomedacc/pulpino/rtl/peripherals.sv
      /home/adam/pulpinomedacc/pulpino/rtl/ram_mux.sv
      /home/adam/pulpinomedacc/pulpino/rtl/pulpino_top.sv
      /home/adam/pulpinomedacc/pulpino/rtl/clk_rst_gen.sv
      /home/adam/pulpinomedacc/pulpino/acc/top_acc.sv
      /home/adam/pulpinomedacc/pulpino/acc/multiply_long.sv
    }
      rt::read_verilog -include {
    /home/adam/pulpinomedacc/pulpino/rtl/includes
    /home/adam/pulpinomedacc/pulpino/ips/axi/axi_node
    /home/adam/pulpinomedacc/pulpino/ips/apb/apb_event_unit/include
    /home/adam/pulpinomedacc/pulpino/ips/fpu
    /home/adam/pulpinomedacc/pulpino/ips/apb/apb_i2c
    /home/adam/pulpinomedacc/pulpino/ips/zero-riscy/include
    /home/adam/pulpinomedacc/pulpino/ips/zero-riscy/include
    /home/adam/pulpinomedacc/pulpino/ips/riscv/include
    /home/adam/pulpinomedacc/pulpino/rtl/includes
    /home/adam/pulpinomedacc/pulpino/ips/riscv/include
    /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl
  } -define {PULP_FPGA_EMUL=1 RISCV} {
      ./.Xil/Vivado-5876-datorn/realtime/xilinx_mem_8192x32_stub.v
      ./.Xil/Vivado-5876-datorn/realtime/xilinx_fp_fma_stub.v
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice_dc/dc_data_buffer.v
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice_dc/dc_full_detector.v
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice_dc/dc_synchronizer.v
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice_dc/dc_token_ring_fifo_din.v
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice_dc/dc_token_ring_fifo_dout.v
      /home/adam/pulpinomedacc/pulpino/ips/axi/axi_slice_dc/dc_token_ring.v
      /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl/adbg_crc32.v
      /home/adam/pulpinomedacc/pulpino/ips/adv_dbg_if/rtl/adbg_tap_top.v
      /home/adam/pulpinomedacc/pulpino/fpga/rtl/pulpino_wrap.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/apb_uart.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/slib_clock_div.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/slib_counter.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/slib_edge_detect.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/slib_fifo.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/slib_input_filter.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/slib_input_sync.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/slib_mv_filter.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/uart_baudgen.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/uart_interrupt.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/uart_receiver.vhd
      /home/adam/pulpinomedacc/pulpino/ips/apb/apb_uart/uart_transmitter.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top pulpino
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-5876-datorn/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -param {
  { USE_ZERO_RISCY 0 }
  { RISCY_RV32F 1 }
  { ZERO_RV32M 0 }
  { ZERO_RV32E 0 }
} -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
